FROM alpine:3.13.2
RUN apk update && apk upgrade

RUN apk add --no-cache make
RUN mkdir /src /dist

COPY Makefile /src/Makefile

# run install without make
RUN install -m 0755 -D /bin/busybox /dist/other-bin/busybox

# run install with make
RUN make -C /src install-bin
